# Generated by Django 2.1.2 on 2018-10-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learncase', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseDetail',
        ),
        migrations.DeleteModel(
            name='CaseSystem',
        ),
    ]
